Reader,Writer: ensure encoding='' is same as encoding=None
This commit makes sure '' behaves the same as None, which is what all the
docstrings say, and would be logical... but then certain things treat them
differently (e.g., file.open(mode='ab', encoding='') throws
ValueError: binary mode doesn't take an encoding argument)